################### tomcat 端口配置  ###################
server:
      port: 9066
      tomcat:
         max-http-post-size: 102400
      max-http-header-size: 10000000
###################  spring配置  ###################
spring:
    # 激活配置文件环境 dev|test|prod
    profiles:
        active: dev
    #数据库驱动
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    mvc:
      static-path-pattern: /static/**
      view:
        prefix: /templates
    http:
      converters:
        preferred-json-mapper: fastjson
      multipart:
        max-file-size: 50Mb
        location: /eric/tem/
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/,file:${qrcode.filePath}

#    devtools:
#      restart:
#        enabled: false #是否开启开发者工具（true/false）
#        additional-paths: src/main/java
#        exclude: static/**,templates/**
    #开启AOP注解
    aop:
      auto: true
      proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
    freemarker:
          content-type: text/html
          template-loader-path: classpath:/templates/ #模板加载路径
          suffix: .html  #后缀名
          enabled: true # Enable MVC view resolution for this technology.
          cache: false #缓存配置
          charset: UTF-8 #编码格式
          settings:
            number_format: '0.##'   #数字格式化


###################  Mybatis配置  ###################
mybatis:
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml
